<?xml version="1.0" encoding="utf-8"?><Database Name="dbQuanLyKaraoke" Class="KaraokeDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\sqlexpress;Initial Catalog=dbQuanLyKaraoke;Integrated Security=True" SettingsObjectName="DAO.Properties.Settings" SettingsPropertyName="dbQuanLyKaraokeConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CALAMVIEC" Member="CALAMVIECs">
    <Type Name="CALAMVIEC">
      <Column Name="MACA" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENCA" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="GIOBD" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="GIOKT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TIENLUONG" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Association Name="CALAMVIEC_PHANCONG" Member="PHANCONGs" ThisKey="MACA" OtherKey="MACA" Type="PHANCONG" />
    </Type>
  </Table>
  <Table Name="dbo.TPMONAN" Member="TPMONANs">
    <Type Name="TPMONAN">
      <Column Name="MAMON" Type="System.String" DbType="Char(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MANL" Type="System.String" DbType="Char(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SOLUONG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="MONAN_TPMONAN" Member="MONAN" ThisKey="MAMON" OtherKey="MAMON" Type="MONAN" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="NGUYENLIEU_TPMONAN" Member="NGUYENLIEU" ThisKey="MANL" OtherKey="MANL" Type="NGUYENLIEU" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CHITIETDATPHONG" Member="CHITIETDATPHONGs">
    <Type Name="CHITIETDATPHONG">
      <Column Name="MADATPHONG" Type="System.String" DbType="Char(7) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MAPHONG" Type="System.String" DbType="Char(4) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="GIOVAO" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="GIORA" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="CHITIETDATPHONG_CHITIETGOIMON" Member="CHITIETGOIMONs" ThisKey="MADATPHONG,MAPHONG" OtherKey="MADATPHONG,MAPHONG" Type="CHITIETGOIMON" />
      <Association Name="PHONG_CHITIETDATPHONG" Member="PHONG" ThisKey="MAPHONG" OtherKey="MAPHONG" Type="PHONG" IsForeignKey="true" />
      <Association Name="THONGTINDATPHONG_CHITIETDATPHONG" Member="THONGTINDATPHONG" ThisKey="MADATPHONG" OtherKey="MADATPHONG" Type="THONGTINDATPHONG" IsForeignKey="true" />
      <Association Name="THONGTINDATPHONG_CHITIETDATPHONG1" Member="THONGTINDATPHONG1" ThisKey="MADATPHONG" OtherKey="MADATPHONG" Type="THONGTINDATPHONG" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CHITIETGOIMON" Member="CHITIETGOIMONs">
    <Type Name="CHITIETGOIMON">
      <Column Name="MADATPHONG" Type="System.String" DbType="Char(7) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MAPHONG" Type="System.String" DbType="Char(4) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MASP" Type="System.String" DbType="Char(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SOLUONG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GIA" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="GIANHAP" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Association Name="CHITIETDATPHONG_CHITIETGOIMON" Member="CHITIETDATPHONG" ThisKey="MADATPHONG,MAPHONG" OtherKey="MADATPHONG,MAPHONG" Type="CHITIETDATPHONG" IsForeignKey="true" />
      <Association Name="SANPHAM_CHITIETGOIMON" Member="SANPHAM" ThisKey="MASP" OtherKey="MASP" Type="SANPHAM" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CHITIETKM" Member="CHITIETKMs">
    <Type Name="CHITIETKM">
      <Column Name="MAKM" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MALOAIKH" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MUCKM" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="KHUYENMAI_CHITIETKM" Member="KHUYENMAI" ThisKey="MAKM" OtherKey="MAKM" Type="KHUYENMAI" IsForeignKey="true" />
      <Association Name="LOAIKHACHHANG_CHITIETKM" Member="LOAIKHACHHANG" ThisKey="MALOAIKH" OtherKey="MALOAIKH" Type="LOAIKHACHHANG" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CHITIETSUDUNGTHIETBI" Member="CHITIETSUDUNGTHIETBIs">
    <Type Name="CHITIETSUDUNGTHIETBI">
      <Column Name="MATB" Type="System.String" DbType="Char(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MASUDUNG" Type="System.String" DbType="VarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SOLUONG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="SUDUNGTHIETBI_CHITIETSUDUNGTHIETBI" Member="SUDUNGTHIETBI" ThisKey="MASUDUNG" OtherKey="MASUDUNG" Type="SUDUNGTHIETBI" IsForeignKey="true" />
      <Association Name="THIETBI_CHITIETSUDUNGTHIETBI" Member="THIETBI" ThisKey="MATB" OtherKey="MATB" Type="THIETBI" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CHUCVU" Member="CHUCVUs">
    <Type Name="CHUCVU">
      <Column Name="MACV" Type="System.String" DbType="Char(4) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENCV" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="HESOLUONG" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="CHUCVU_NHANVIEN" Member="NHANVIENs" ThisKey="MACV" OtherKey="MACV" Type="NHANVIEN" />
      <Association Name="CHUCVU_PHANQUYEN" Member="PHANQUYENs" ThisKey="MACV" OtherKey="MACV" Type="PHANQUYEN" />
    </Type>
  </Table>
  <Table Name="dbo.CTPNSP" Member="CTPNSPs">
    <Type Name="CTPNSP">
      <Column Name="MASP" Type="System.String" DbType="Char(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SOPNSP" Type="System.String" DbType="Char(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SOLUONGNHAP" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="PHIEUNHAPSANPHAM_CTPNSP" Member="PHIEUNHAPSANPHAM" ThisKey="SOPNSP" OtherKey="SOPNSP" Type="PHIEUNHAPSANPHAM" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="SANPHAM_CTPNSP" Member="SANPHAM" ThisKey="MASP" OtherKey="MASP" Type="SANPHAM" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CTPNTB" Member="CTPNTBs">
    <Type Name="CTPNTB">
      <Column Name="MATB" Type="System.String" DbType="Char(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SOPNTB" Type="System.String" DbType="Char(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SOLUONGNHAP" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="PHIEUNHAPTHIETBI_CTPNTB" Member="PHIEUNHAPTHIETBI" ThisKey="SOPNTB" OtherKey="SOPNTB" Type="PHIEUNHAPTHIETBI" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="THIETBI_CTPNTB" Member="THIETBI" ThisKey="MATB" OtherKey="MATB" Type="THIETBI" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DANGSUDUNG" Member="DANGSUDUNGs">
    <Type Name="DANGSUDUNG">
      <Column Name="MAPHONG" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="SOHD" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DOANHTHU" Member="DOANHTHUs">
    <Type Name="DOANHTHU">
      <Column Name="THANG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NAM" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TONGDOANHTHU" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DONVI" Member="DONVIs">
    <Type Name="DONVI">
      <Column Name="MADV" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENDV" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="DONVI_SANPHAM" Member="SANPHAMs" ThisKey="MADV" OtherKey="DVT" Type="SANPHAM" />
    </Type>
  </Table>
  <Table Name="dbo.HOADON" Member="HOADONs">
    <Type Name="HOADON">
      <Column Name="MAHD" Type="System.String" DbType="Char(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MADATPHONG" Type="System.String" DbType="Char(7) NOT NULL" CanBeNull="false" />
      <Column Name="NGAYGIOLAP" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="THANHTIEN" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Association Name="THONGTINDATPHONG_HOADON" Member="THONGTINDATPHONG" ThisKey="MADATPHONG" OtherKey="MADATPHONG" Type="THONGTINDATPHONG" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KHACHHANG" Member="KHACHHANGs">
    <Type Name="KHACHHANG">
      <Column Name="MAKH" Type="System.String" DbType="Char(7) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MALOAIKH" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TENKH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="NVarChar(11)" CanBeNull="true" />
      <Association Name="KHACHHANG_THONGTINDATPHONG" Member="THONGTINDATPHONGs" ThisKey="MAKH" OtherKey="MAKH" Type="THONGTINDATPHONG" />
      <Association Name="LOAIKHACHHANG_KHACHHANG" Member="LOAIKHACHHANG" ThisKey="MALOAIKH" OtherKey="MALOAIKH" Type="LOAIKHACHHANG" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.KHUYENMAI" Member="KHUYENMAIs">
    <Type Name="KHUYENMAI">
      <Column Name="MAKM" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENKM" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NGAYBD" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="NGAYKT" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Association Name="KHUYENMAI_CHITIETKM" Member="CHITIETKMs" ThisKey="MAKM" OtherKey="MAKM" Type="CHITIETKM" />
    </Type>
  </Table>
  <Table Name="dbo.LOAIKHACHHANG" Member="LOAIKHACHHANGs">
    <Type Name="LOAIKHACHHANG">
      <Column Name="MALOAIKH" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENLOAIKH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SOTIEMTICHLUY" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="LOAIKHACHHANG_CHITIETKM" Member="CHITIETKMs" ThisKey="MALOAIKH" OtherKey="MALOAIKH" Type="CHITIETKM" />
      <Association Name="LOAIKHACHHANG_KHACHHANG" Member="KHACHHANGs" ThisKey="MALOAIKH" OtherKey="MALOAIKH" Type="KHACHHANG" />
    </Type>
  </Table>
  <Table Name="dbo.LOAIMONAN" Member="LOAIMONANs">
    <Type Name="LOAIMONAN">
      <Column Name="MA" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENLOAI" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="LOAIMONAN_MONAN" Member="MONANs" ThisKey="MA" OtherKey="LOAIMON" Type="MONAN" />
    </Type>
  </Table>
  <Table Name="dbo.LOAIPHONG" Member="LOAIPHONGs">
    <Type Name="LOAIPHONG">
      <Column Name="MALOAIPHONG" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENLOAIPHONG" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GIA" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Association Name="LOAIPHONG_PHONG" Member="PHONGs" ThisKey="MALOAIPHONG" OtherKey="MALOAIPHONG" Type="PHONG" />
    </Type>
  </Table>
  <Table Name="dbo.LOAISANPHAM" Member="LOAISANPHAMs">
    <Type Name="LOAISANPHAM">
      <Column Name="MA" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENLOAI" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="LOAISANPHAM_SANPHAM" Member="SANPHAMs" ThisKey="MA" OtherKey="LOAISP" Type="SANPHAM" />
    </Type>
  </Table>
  <Table Name="dbo.LUONG" Member="LUONGs">
    <Type Name="LUONG">
      <Column Name="MANV" Type="System.String" DbType="Char(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="THANGLUONG" Type="System.String" DbType="Char(7) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SOTIEN" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Association Name="NHANVIEN_LUONG" Member="NHANVIEN" ThisKey="MANV" OtherKey="MANV" Type="NHANVIEN" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MONAN" Member="MONANs">
    <Type Name="MONAN">
      <Column Name="MAMON" Type="System.String" DbType="Char(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENMON" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LOAIMON" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ANHMINHHOA" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DONGIA" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Association Name="MONAN_TPMONAN" Member="TPMONANs" ThisKey="MAMON" OtherKey="MAMON" Type="TPMONAN" />
      <Association Name="LOAIMONAN_MONAN" Member="LOAIMONAN" ThisKey="LOAIMON" OtherKey="MA" Type="LOAIMONAN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NGAYLAMVIEC" Member="NGAYLAMVIECs">
    <Type Name="NGAYLAMVIEC">
      <Column Name="Ngay" Type="System.DateTime" DbType="Date NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="NGAYLAMVIEC_PHANCONG" Member="PHANCONGs" ThisKey="Ngay" OtherKey="NGAY" Type="PHANCONG" />
    </Type>
  </Table>
  <Table Name="dbo.NGUYENLIEU" Member="NGUYENLIEUs">
    <Type Name="NGUYENLIEU">
      <Column Name="MANL" Type="System.String" DbType="Char(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MANCC" Type="System.String" DbType="Char(5) NOT NULL" CanBeNull="false" />
      <Column Name="TENNL" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LOAINL" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DVT" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="DONGIA" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="SLTON" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SLTOITHIEU" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DONGIANHAP" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="NGUYENLIEU_TPMONAN" Member="TPMONANs" ThisKey="MANL" OtherKey="MANL" Type="TPMONAN" />
      <Association Name="NHACUNGCAP_NGUYENLIEU" Member="NHACUNGCAP" ThisKey="MANCC" OtherKey="MANCC" Type="NHACUNGCAP" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.NHACUNGCAP" Member="NHACUNGCAPs">
    <Type Name="NHACUNGCAP">
      <Column Name="MANCC" Type="System.String" DbType="Char(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENNCC" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="NVarChar(11)" CanBeNull="true" />
      <Column Name="DIACHI" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="LOAIHANGCC" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="NHACUNGCAP_NGUYENLIEU" Member="NGUYENLIEUs" ThisKey="MANCC" OtherKey="MANCC" Type="NGUYENLIEU" />
      <Association Name="NHACUNGCAP_SANPHAM" Member="SANPHAMs" ThisKey="MANCC" OtherKey="MANCC" Type="SANPHAM" />
      <Association Name="NHACUNGCAP_THIETBI" Member="THIETBIs" ThisKey="MANCC" OtherKey="MANCC" Type="THIETBI" />
    </Type>
  </Table>
  <Table Name="dbo.NHANVIEN" Member="NHANVIENs">
    <Type Name="NHANVIEN">
      <Column Name="MANV" Type="System.String" DbType="Char(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENTK" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="MACV" Type="System.String" DbType="Char(4)" CanBeNull="true" />
      <Column Name="TENNV" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="NVarChar(11)" CanBeNull="true" />
      <Column Name="DIACHI" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="NHANVIEN_LUONG" Member="LUONGs" ThisKey="MANV" OtherKey="MANV" Type="LUONG" />
      <Association Name="NHANVIEN_PHANCONG" Member="PHANCONGs" ThisKey="MANV" OtherKey="MANV" Type="PHANCONG" />
      <Association Name="NHANVIEN_PHIEUNHAPNGUYENLIEU" Member="PHIEUNHAPNGUYENLIEUs" ThisKey="MANV" OtherKey="MANV" Type="PHIEUNHAPNGUYENLIEU" />
      <Association Name="NHANVIEN_PHIEUNHAPSANPHAM" Member="PHIEUNHAPSANPHAMs" ThisKey="MANV" OtherKey="MANV" Type="PHIEUNHAPSANPHAM" />
      <Association Name="NHANVIEN_THONGTINDATPHONG" Member="THONGTINDATPHONGs" ThisKey="MANV" OtherKey="MANV" Type="THONGTINDATPHONG" />
      <Association Name="CHUCVU_NHANVIEN" Member="CHUCVU" ThisKey="MACV" OtherKey="MACV" Type="CHUCVU" IsForeignKey="true" />
      <Association Name="TAIKHOAN_NHANVIEN" Member="TAIKHOAN" ThisKey="TENTK" OtherKey="TENTK" Type="TAIKHOAN" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.PHANCONG" Member="PHANCONGs">
    <Type Name="PHANCONG">
      <Column Name="MANV" Type="System.String" DbType="Char(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MACA" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NGAY" Type="System.DateTime" DbType="Date NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="NGAYLAMVIEC_PHANCONG" Member="NGAYLAMVIEC" ThisKey="NGAY" OtherKey="Ngay" Type="NGAYLAMVIEC" IsForeignKey="true" />
      <Association Name="NHANVIEN_PHANCONG" Member="NHANVIEN" ThisKey="MANV" OtherKey="MANV" Type="NHANVIEN" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="CALAMVIEC_PHANCONG" Member="CALAMVIEC" ThisKey="MACA" OtherKey="MACA" Type="CALAMVIEC" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PHANQUYEN" Member="PHANQUYENs">
    <Type Name="PHANQUYEN">
      <Column Name="MACV" Type="System.String" DbType="Char(4) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MAQUYEN" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="CHUCVU_PHANQUYEN" Member="CHUCVU" ThisKey="MACV" OtherKey="MACV" Type="CHUCVU" IsForeignKey="true" />
      <Association Name="QUYEN_PHANQUYEN" Member="QUYEN" ThisKey="MAQUYEN" OtherKey="MAQUYEN" Type="QUYEN" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PHIEUNHAPNGUYENLIEU" Member="PHIEUNHAPNGUYENLIEUs">
    <Type Name="PHIEUNHAPNGUYENLIEU">
      <Column Name="SOPNNL" Type="System.String" DbType="Char(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MANV" Type="System.String" DbType="Char(5) NOT NULL" CanBeNull="false" />
      <Column Name="NGAYDAT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NGAYGIAO" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="THANHTIEN" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="NGUOIGIAO" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MANCC" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Association Name="NHANVIEN_PHIEUNHAPNGUYENLIEU" Member="NHANVIEN" ThisKey="MANV" OtherKey="MANV" Type="NHANVIEN" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PHIEUNHAPSANPHAM" Member="PHIEUNHAPSANPHAMs">
    <Type Name="PHIEUNHAPSANPHAM">
      <Column Name="SOPNSP" Type="System.String" DbType="Char(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MANV" Type="System.String" DbType="Char(5)" CanBeNull="true" />
      <Column Name="NGAYDAT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NGAYGIAO" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="THANHTIEN" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="NGUOIGIAO" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MANCC" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Association Name="PHIEUNHAPSANPHAM_CTPNSP" Member="CTPNSPs" ThisKey="SOPNSP" OtherKey="SOPNSP" Type="CTPNSP" />
      <Association Name="NHANVIEN_PHIEUNHAPSANPHAM" Member="NHANVIEN" ThisKey="MANV" OtherKey="MANV" Type="NHANVIEN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PHIEUNHAPTHIETBI" Member="PHIEUNHAPTHIETBIs">
    <Type Name="PHIEUNHAPTHIETBI">
      <Column Name="SOPNTB" Type="System.String" DbType="Char(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MANV" Type="System.String" DbType="Char(5) NOT NULL" CanBeNull="false" />
      <Column Name="NGAYDAT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NGAYGIAO" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="THANHTIEN" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="NGUOIGIAO" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MANCC" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Association Name="PHIEUNHAPTHIETBI_CTPNTB" Member="CTPNTBs" ThisKey="SOPNTB" OtherKey="SOPNTB" Type="CTPNTB" />
    </Type>
  </Table>
  <Table Name="dbo.PHONG" Member="PHONGs">
    <Type Name="PHONG">
      <Column Name="MAPHONG" Type="System.String" DbType="Char(4) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MALOAIPHONG" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TINHTRANG" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Association Name="PHONG_CHITIETDATPHONG" Member="CHITIETDATPHONGs" ThisKey="MAPHONG" OtherKey="MAPHONG" Type="CHITIETDATPHONG" />
      <Association Name="LOAIPHONG_PHONG" Member="LOAIPHONG" ThisKey="MALOAIPHONG" OtherKey="MALOAIPHONG" Type="LOAIPHONG" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.QUYDINHTHANHVIEN" Member="QUYDINHTHANHVIENs">
    <Type Name="QUYDINHTHANHVIEN">
      <Column Name="MALOAIKH" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SOTIENTICHLUY" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.QUYEN" Member="QUYENs">
    <Type Name="QUYEN">
      <Column Name="MAQUYEN" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENQUYEN" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="QUYEN_PHANQUYEN" Member="PHANQUYENs" ThisKey="MAQUYEN" OtherKey="MAQUYEN" Type="PHANQUYEN" />
    </Type>
  </Table>
  <Table Name="dbo.SANPHAM" Member="SANPHAMs">
    <Type Name="SANPHAM">
      <Column Name="MASP" Type="System.String" DbType="Char(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MANCC" Type="System.String" DbType="Char(5)" CanBeNull="true" />
      <Column Name="TENSP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LOAISP" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ANHMINHHOA" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DONGIA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SLTON" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SLTOITHIEU" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DONGIANHAP" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="DVT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="SANPHAM_CHITIETGOIMON" Member="CHITIETGOIMONs" ThisKey="MASP" OtherKey="MASP" Type="CHITIETGOIMON" />
      <Association Name="SANPHAM_CTPNSP" Member="CTPNSPs" ThisKey="MASP" OtherKey="MASP" Type="CTPNSP" />
      <Association Name="LOAISANPHAM_SANPHAM" Member="LOAISANPHAM" ThisKey="LOAISP" OtherKey="MA" Type="LOAISANPHAM" IsForeignKey="true" />
      <Association Name="NHACUNGCAP_SANPHAM" Member="NHACUNGCAP" ThisKey="MANCC" OtherKey="MANCC" Type="NHACUNGCAP" IsForeignKey="true" DeleteRule="CASCADE" />
      <Association Name="DONVI_SANPHAM" Member="DONVI" ThisKey="DVT" OtherKey="MADV" Type="DONVI" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SUDUNGTHIETBI" Member="SUDUNGTHIETBIs">
    <Type Name="SUDUNGTHIETBI">
      <Column Name="MASUDUNG" Type="System.String" DbType="VarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="LYDO" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NGAY" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Association Name="SUDUNGTHIETBI_CHITIETSUDUNGTHIETBI" Member="CHITIETSUDUNGTHIETBIs" ThisKey="MASUDUNG" OtherKey="MASUDUNG" Type="CHITIETSUDUNGTHIETBI" />
    </Type>
  </Table>
  <Table Name="dbo.TAIKHOAN" Member="TAIKHOANs">
    <Type Name="TAIKHOAN">
      <Column Name="TENTK" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MATKHAU" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="TAIKHOAN_NHANVIEN" Member="NHANVIENs" ThisKey="TENTK" OtherKey="TENTK" Type="NHANVIEN" />
    </Type>
  </Table>
  <Table Name="dbo.TAOMA" Member="TAOMAs">
    <Type Name="TAOMA">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Ten" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="SOMA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MACUOI" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TIENTO" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.THAMSO" Member="THAMSOs">
    <Type Name="THAMSO">
      <Column Name="MATHAMSO" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENTHAMSO" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GIATRI" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.THIETBI" Member="THIETBIs">
    <Type Name="THIETBI">
      <Column Name="MATB" Type="System.String" DbType="Char(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MANCC" Type="System.String" DbType="Char(5) NOT NULL" CanBeNull="false" />
      <Column Name="TENTB" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LOAITB" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="DVT" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="DONGIA" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="SLTON" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SLTOITHIEU" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="THIETBI_CHITIETSUDUNGTHIETBI" Member="CHITIETSUDUNGTHIETBIs" ThisKey="MATB" OtherKey="MATB" Type="CHITIETSUDUNGTHIETBI" />
      <Association Name="THIETBI_CTPNTB" Member="CTPNTBs" ThisKey="MATB" OtherKey="MATB" Type="CTPNTB" />
      <Association Name="NHACUNGCAP_THIETBI" Member="NHACUNGCAP" ThisKey="MANCC" OtherKey="MANCC" Type="NHACUNGCAP" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.THONGTINDATPHONG" Member="THONGTINDATPHONGs">
    <Type Name="THONGTINDATPHONG">
      <Column Name="MADATPHONG" Type="System.String" DbType="Char(7) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MAKH" Type="System.String" DbType="Char(7) NOT NULL" CanBeNull="false" />
      <Column Name="NGAYDAT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NGAYNHAN" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MANV" Type="System.String" DbType="Char(5) NOT NULL" CanBeNull="false" />
      <Column Name="TIENCOC" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="GIAMGIA" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="DATHANHTOAN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="THONGTINDATPHONG_CHITIETDATPHONG" Member="CHITIETDATPHONGs" ThisKey="MADATPHONG" OtherKey="MADATPHONG" Type="CHITIETDATPHONG" />
      <Association Name="THONGTINDATPHONG_CHITIETDATPHONG1" Member="CHITIETDATPHONGs1" ThisKey="MADATPHONG" OtherKey="MADATPHONG" Type="CHITIETDATPHONG" />
      <Association Name="THONGTINDATPHONG_HOADON" Member="HOADONs" ThisKey="MADATPHONG" OtherKey="MADATPHONG" Type="HOADON" />
      <Association Name="KHACHHANG_THONGTINDATPHONG" Member="KHACHHANG" ThisKey="MAKH" OtherKey="MAKH" Type="KHACHHANG" IsForeignKey="true" />
      <Association Name="NHANVIEN_THONGTINDATPHONG" Member="NHANVIEN" ThisKey="MANV" OtherKey="MANV" Type="NHANVIEN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TONKHOCT" Member="TONKHOCTs">
    <Type Name="TONKHOCT">
      <Column Name="MA" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="TONDAU" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SOLUONGNHAP" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SOLUONGXUAT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NGAY" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </Type>
  </Table>
</Database>